name: take-me-home
main: me.carbon.plugins.takemehome.TakeMeHome
version: "1.0.0"
api-version: "1.16"
author: Carbon
description: "A simple plugin that allows players to teleport back to their bed."

commands:
  home:
    description: "Send the player invoking the command back to their bed."
    usage: /home